// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ZvwJ8NiabP3T3a076_vBIwoMa1FOGXg',
    appId: '1:123043512276:web:3456fa82cd75e07443a041',
    messagingSenderId: '123043512276',
    projectId: 'adedonha-d46b4',
    authDomain: 'adedonha-d46b4.firebaseapp.com',
    storageBucket: 'adedonha-d46b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTBGOs8esypewhG-sp-A6BnSzrkwMk8xQ',
    appId: '1:123043512276:android:0aebc2cc7f2b9f5d43a041',
    messagingSenderId: '123043512276',
    projectId: 'adedonha-d46b4',
    storageBucket: 'adedonha-d46b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_vFDRNHdQ54k7ltg2Yc0KffAwOqn1HHw',
    appId: '1:123043512276:ios:9d22ac998ddd319143a041',
    messagingSenderId: '123043512276',
    projectId: 'adedonha-d46b4',
    storageBucket: 'adedonha-d46b4.firebasestorage.app',
    iosBundleId: 'com.example.adedonha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_vFDRNHdQ54k7ltg2Yc0KffAwOqn1HHw',
    appId: '1:123043512276:ios:9d22ac998ddd319143a041',
    messagingSenderId: '123043512276',
    projectId: 'adedonha-d46b4',
    storageBucket: 'adedonha-d46b4.firebasestorage.app',
    iosBundleId: 'com.example.adedonha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ZvwJ8NiabP3T3a076_vBIwoMa1FOGXg',
    appId: '1:123043512276:web:c550021a05db937443a041',
    messagingSenderId: '123043512276',
    projectId: 'adedonha-d46b4',
    authDomain: 'adedonha-d46b4.firebaseapp.com',
    storageBucket: 'adedonha-d46b4.firebasestorage.app',
  );
}
